application: subtle42
version: 5
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: interface/images
  
- url: /stylesheets
  static_dir: interface/stylesheets

- url: /javascript
  static_dir: interface/javascript
  
- url: /.*
  script: main.py

